// Types for the vendored Go WASM runtime.
//
// `src/prover/wasm_exec.js` is generated by `scripts/sync-wasm.mjs` from the Go
// toolchain that built `mist.wasm`, and is deliberately not type-checked or
// edited by hand. It has no exports: importing it for the side effect of
// registering `globalThis.Go` is the whole point, so this declaration exists
// only to give that import a type.
export {};
